package main

import "strings"

// The overlay: a panel over the transcript, in one of two modes.
//
// "c" shows the Cypher the current stage runs, so "graph-selected" and
// "recorded in the graph" can be checked rather than believed. "e" shows the
// JFrog Evidence predicate the final step produced, so the same is true of
// "attested".
//
// Neither is written here. The queries come from `monograph queries --json` and
// the predicate from `monograph evidence` -- both at run time, from the same
// binary the demo executes, because the entire value of showing them is that
// they cannot be a copy that has drifted.

// overlayMode is which document the panel is showing. One panel with a mode,
// not two panels: the open overlay owns the keyboard (see Update), and a second
// code path would sooner or later disagree with the first about which keys close
// it or how the transcript underneath is preserved.
type overlayMode int

const (
	modeCypher overlayMode = iota
	modeEvidence
)

// cypherStage names the pipeline stage whose Cypher a phase should show, or ""
// for a phase that touches no graph at all.
//
// EDIT and RUN are deliberately empty: EDIT is git and RUN is Dagger, and
// offering a query for either would imply the graph is involved in work it has
// nothing to do with.
func cypherStage(p Phase) string {
	switch p {
	case phaseBeat2Select, phaseBeat3Select, phaseBeat4Select:
		return "select"
	case phaseBeat3Record, phaseBeat4Record:
		return "record"
	case phaseEvidence:
		// The evidence step is a READ, and showing its query is the point: it is
		// what makes "the predicate is a serialisation of the graph" checkable
		// instead of asserted.
		return "evidence"
	}
	return ""
}

// cypherFor picks the queries to show for a phase, in the order they should be
// read.
//
// The per-phase filtering is the honest part. RecordProvenByQuery executes only
// when a plan reused something, which is beat 4's record and not beat 3's -- so
// showing it at beat 3 would put a query on screen that the step the audience
// just watched did not run.
func cypherFor(p Phase, all []CypherQuery) []CypherQuery {
	stage := cypherStage(p)
	if stage == "" {
		return nil
	}
	var out []CypherQuery
	for _, q := range all {
		if q.Stage != stage {
			continue
		}
		if p == phaseBeat3Record && q.Name == "record-proven-by" {
			continue // nothing was skipped here, so this one does not fire
		}
		out = append(out, q)
	}
	// At beat 4's record, lead with the query that fires in THIS step rather
	// than with the one that also ran a beat ago.
	if p == phaseBeat4Record {
		for i, q := range out {
			if q.Name == "record-proven-by" && i != 0 {
				out = append([]CypherQuery{q}, append(out[:i:i], out[i+1:]...)...)
				break
			}
		}
	}
	return out
}

// cypherPanelBody is the panel's text, unbordered and unwrapped -- the caller
// sizes and frames it.
func cypherPanelBody(p Phase, all []CypherQuery, loadErr error) string {
	if loadErr != nil {
		return failStyle.Render("could not read the queries from monograph:") + "\n" +
			dimStyle.Render(loadErr.Error()) + "\n\n" +
			noteStyle.Render("`monograph queries --json` is what this panel shows.")
	}

	qs := cypherFor(p, all)
	if len(qs) == 0 {
		return noteStyle.Render("No Cypher at this stage.") + "\n\n" +
			dimStyle.Render("EDIT is git and RUN is Dagger -- neither touches the graph.") + "\n" +
			dimStyle.Render("The graph is read at SELECT and written at RECORD.")
	}

	var b strings.Builder
	for i, q := range qs {
		if i > 0 {
			b.WriteString("\n") // the previous block already ends in a newline
		}
		kind := "READ"
		if q.Kind == "write" {
			kind = "WRITE"
		}
		b.WriteString(titleStyle.Render(kind + " -- " + q.Title))
		b.WriteString("\n")
		b.WriteString(dimStyle.Render("runs: " + q.When))
		b.WriteString("\n")
		for _, line := range strings.Split(strings.TrimSpace(q.Cypher), "\n") {
			b.WriteString(cypherStyle.Render(line))
			b.WriteString("\n")
		}
	}
	return strings.TrimRight(b.String(), "\n")
}

// evidencePanelBody is the JFrog Evidence predicate as the tool emitted it,
// followed by the command that would upload it.
//
// Verbatim, both of them. The panel exists so the audience can read the actual
// document rather than a summary of it -- a rendered-from-fields version would
// be a second implementation of the predicate, and the one on screen would be
// the one nobody signs. Same reason the Cypher panel reads `monograph queries`
// instead of holding its own copy of the queries.
func evidencePanelBody(predicate, command string) string {
	if predicate == "" {
		return noteStyle.Render("No predicate yet.") + "\n\n" +
			dimStyle.Render("It is generated by the final step, from the run the graph") + "\n" +
			dimStyle.Render("has just recorded.")
	}

	var b strings.Builder
	b.WriteString(titleStyle.Render("PREDICATE -- read back from the graph, not assembled from files"))
	b.WriteString("\n")
	b.WriteString(dimStyle.Render("in-toto predicate body; `jf evd create` signs it and binds it to a subject"))
	b.WriteString("\n")
	for _, line := range strings.Split(strings.TrimSpace(predicate), "\n") {
		b.WriteString(cypherStyle.Render(line))
		b.WriteString("\n")
	}
	if command != "" {
		b.WriteString("\n")
		b.WriteString(titleStyle.Render("UPLOAD -- not run by this demo"))
		b.WriteString("\n")
		b.WriteString(dimStyle.Render("needs a subject in Artifactory and a signing key; see ADR-003"))
		b.WriteString("\n")
		for _, line := range strings.Split(strings.TrimSpace(command), "\n") {
			b.WriteString(evidenceStyle.Render(line))
			b.WriteString("\n")
		}
	}
	return strings.TrimRight(b.String(), "\n")
}

// cypherPanel frames the given already-scrolled content so the result is EXACTLY
// width x height cells.
//
// Exactly, because this is rendered in place of the transcript viewport rather
// than composited on top of it. Overlaying properly would mean slicing rendered
// lines that are full of ANSI escapes, and cutting a styled line by column is
// how colour ends up bleeding across a screen. Occupying the viewport's slot
// instead keeps the diagram and the status line where they were -- the panel
// covers what it should cover and nothing shifts.
func cypherPanel(content string, width, height int) string {
	// Width-2, not width-4: lipgloss counts padding inside Width but the border
	// outside it, so the two padding columns must be included here and only the
	// two border columns subtracted. Getting this wrong left the panel two cells
	// narrower than the slot it covers.
	return overlayStyle.
		Width(max(1, width-2)).
		Height(max(1, height-2)).
		Render(content)
}

// overlayInner is the content area a panel of this size leaves: two columns and
// two rows for the border, plus one column of padding on each side.
func overlayInner(width, height int) (int, int) {
	return max(10, width-4), max(1, height-2)
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
