// One-off backfill: give every pre-existing :CIRun a createdAt.
//
// WHY THIS EXISTS
// ---------------
// `record` stamps CIRun.createdAt server-side on insert, but only from the
// commit that added it. Runs recorded before that carry no createdAt at all,
// and a NULL here is not merely missing data -- it is a wrong answer:
//
//     MATCH (r:CIRun) RETURN r.id ORDER BY r.createdAt DESC LIMIT 1
//
// Neo4j sorts NULL FIRST in descending order, so "the latest run" comes back as
// whichever un-backfilled old node the planner reaches first. The query looks
// right and lies. Backfilling every node is what makes it correct.
//
// WHERE THE TIMESTAMPS COME FROM
// ------------------------------
// Not from datetime() -- stamping 29 historical runs with "now" would flatten
// them into one instant and destroy the ordering this is for. Every run id
// generated by bench/demo.sh and bench/demotui ends in the epoch its nonce was
// minted at, so the real creation time is recoverable from the id itself:
//
//     demo-core-83229-1786604520              <- pid + epoch SECONDS   (10 digits)
//     demo-core-e2e-test-1786604955990043000  <- epoch NANOSECONDS     (19 digits)
//
// The two units are why this branches on digit count rather than assuming one.
// Feeding nanoseconds to epochSeconds yields a year in the 58,000s, and those
// rows would then sort as "latest" forever -- the exact bug being fixed here.
// Any id whose tail is not one of the two known epoch shapes is left NULL and
// reported by the verification query below, rather than being guessed at.
//
// IDEMPOTENT: only touches nodes that have no createdAt, so re-running it can
// never overwrite a server-stamped value with a derived one.

MATCH (r:CIRun)
WHERE r.createdAt IS NULL
WITH r, last(split(r.id, '-')) AS tail
WHERE tail =~ '\\d+'
WITH r, tail, size(tail) AS digits
SET r.createdAt = CASE digits
  WHEN 10 THEN datetime({epochSeconds: toInteger(tail)})
  WHEN 19 THEN datetime({epochMillis: toInteger(tail) / 1000000})
  ELSE NULL
END
RETURN digits AS epochDigits, count(*) AS nodesBackfilled
ORDER BY epochDigits;

// ---------------------------------------------------------------- verification
// Run this after the backfill. A count of updated nodes proves nothing about
// correctness -- a unit mix-up updates every row and still puts them in the
// wrong millennium -- so this asserts the timestamps landed in a plausible
// window and that nothing was left behind.
//
//     MATCH (r:CIRun)
//     RETURN count(*)                                            AS runs,
//            count(r.createdAt)                                  AS withCreatedAt,
//            min(r.createdAt)                                    AS earliest,
//            max(r.createdAt)                                    AS latest,
//            count(CASE WHEN r.createdAt < datetime('2025-01-01T00:00:00Z')
//                        OR r.createdAt > datetime() THEN 1 END) AS outOfRange;
//
// Expected: withCreatedAt = runs, outOfRange = 0, and both bounds inside the
// period this repository has existed.
